require "minitest/autorun"
require 'minitest/pride'

require './lib/sales_engine'
require './lib/customer'
require './lib/customer_repository'
require './lib/invoice_item'
require './lib/invoice_item_repository'
require './lib/repository'
require './lib/invoice_repository'
# require './lib/parser'
require './lib/model_object'
require './lib/item'
require './lib/merchant'
require './lib/transaction'
require './lib/merchant_repository'